/* eslint-disable react/no-unescaped-entities */
"use client";

import { useState } from "react";

const methods = [{ id: "D17", title: "D17", subtitle: "Paiement mobile", instructions: "Numéro D17 : 21 000 319\nTitulaire : Ayhem", tone: "bg-[#e8f2f8]" }, { id: "BANK_TRANSFER", title: "Virement bancaire", subtitle: "BTE", instructions: "RIB : 24031147426251110157\nTitulaire : Ayhem", tone: "bg-[#eef0f7]" }, { id: "FLOUCI", title: "Flouci", subtitle: "Paiement mobile", instructions: "Numéro : 21 000 319\nTitulaire : Ayhem", tone: "bg-[#fff0e7]" }, { id: "ZITOUNA", title: "Paiement Zitouna", subtitle: "Paiement mobile", instructions: "Numéro : 21 000 319\nTitulaire : Ayhem", tone: "bg-[#eaf6ef]" }];

export default function AddMoneyPage() { const [method, setMethod] = useState(methods[0]); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/wallet/deposits", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amountMillimes: Math.round(Number(data.get("amount")) * 1000), method: method.id, reference: data.get("reference") }) }); const result = await response.json().catch(() => ({})); setPending(false); setMessage(response.ok ? result.message : result.error ?? "Impossible d'envoyer la demande."); if (response.ok) event.currentTarget.reset(); }
 return <main className="min-h-screen bg-[#f4f6fa] text-[#11233f]"><header className="border-b border-slate-200 bg-white px-4 py-4 sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="/dashboard/wallet" className="font-bold">← Wallet</a><a href="/dashboard" className="text-2xl font-bold tracking-[-.06em]">profy<span className="text-[#0d8d78]">.tn</span></a></div></header><section className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-12"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0d8d78]">Recharge wallet</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Ajouter de l'argent</h1><p className="mt-3 text-slate-500">Choisis un moyen, effectue le paiement, puis envoie la référence. Ton solde reste inchangé jusqu'à validation.</p><div className="mt-8 grid gap-4">{methods.map((item) => <button type="button" key={item.id} onClick={() => setMethod(item)} className={`rounded-3xl border p-5 text-left transition duration-300 hover:-translate-y-1 hover:shadow-lg ${method.id === item.id ? "border-[#0d8d78] ring-2 ring-[#b9e6dc]" : "border-slate-200 bg-white"}`}><div className="flex items-center gap-4"><div className={`flex h-16 w-16 items-center justify-center rounded-2xl ${item.tone} text-sm font-bold`}>{item.title === "Virement bancaire" ? "BTE" : item.title}</div><div><h2 className="text-lg font-bold">{item.title}</h2><p className="mt-1 text-sm text-slate-500">{item.subtitle}</p></div><span className="ml-auto text-xl">{method.id === item.id ? "●" : "○"}</span></div><div className="mt-5 whitespace-pre-line rounded-xl bg-white/70 p-3 text-sm text-slate-600">{item.instructions}</div></button>)}</div><form onSubmit={submit} className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Envoyer une demande de dépôt</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Montant à déposer (DT)<input name="amount" required min="1" step="0.001" type="number" placeholder="Ex : 50" className="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-[#0d8d78]" /></label><label className="text-sm font-semibold">Référence de transaction<input name="reference" required placeholder="Référence affichée après paiement" className="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-[#0d8d78]" /></label></div>{message && <p className="mt-4 rounded-xl bg-[#e5f7f2] p-3 text-sm font-semibold text-[#0d8d78]">{message}</p>}<button disabled={pending} className="mt-5 w-full rounded-xl bg-[#11233f] px-4 py-3 font-bold text-white transition hover:bg-[#0d8d78] disabled:opacity-50">{pending ? "Envoi..." : `Envoyer via ${method.title}`}</button></form></section></main>;
}
