/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-location-assign-relative-destination, react/no-unescaped-entities */
"use client";

import { useState } from "react";
import { subjects, governorates } from "@/lib/domain/catalog";

const days = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"];

export default function TeacherOnboardingPage() {
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const data = new FormData(event.currentTarget); const availability = days.flatMap((_, dayOfWeek) => { const startTime = String(data.get(`start-${dayOfWeek}`) ?? ""); const endTime = String(data.get(`end-${dayOfWeek}`) ?? ""); return startTime && endTime ? [{ dayOfWeek, startTime, endTime }] : []; }); const result = await fetch("/api/teacher/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: data.get("title"), bio: data.get("bio"), experienceYears: Number(data.get("experienceYears")), hourlyRateMillimes: Math.round(Number(data.get("hourlyRate")) * 1000), governorate: data.get("governorate"), city: data.get("city"), online: data.get("online") === "on", inPerson: data.get("inPerson") === "on", subjects: data.getAll("subjects"), availability }) }); const body = await result.json().catch(() => ({})); setPending(false); setMessage(result.ok ? body.message : body.error ?? "Erreur"); if (result.ok) setTimeout(() => { window.location.href = "/teacher/dashboard"; }, 1200); }
  return <main className="min-h-screen bg-[#f8fafc] px-6 py-10 text-[#11233f]"><div className="mx-auto max-w-4xl"><a href="/" className="text-2xl font-bold tracking-[-.06em]">profy<span className="text-[#0d8d78]">.tn</span></a><form onSubmit={submit} className="mt-10 space-y-6 rounded-3xl bg-white p-6 shadow-sm sm:p-10"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#0d8d78]">Candidature professeur</p><h1 className="mt-2 text-4xl font-bold">Construis ton profil.</h1><p className="mt-3 text-slate-500">Ton profil restera en attente jusqu'à validation par l'administration.</p></div><section className="grid gap-4 sm:grid-cols-2"><input name="title" required placeholder="Titre professionnel" className="rounded-xl border border-slate-200 p-3 sm:col-span-2" /><textarea name="bio" required placeholder="Présente ton expérience et ta méthode" rows={5} className="rounded-xl border border-slate-200 p-3 sm:col-span-2" /><input name="experienceYears" required type="number" min="0" placeholder="Années d'expérience" className="rounded-xl border border-slate-200 p-3" /><input name="hourlyRate" required type="number" min="1" step="0.001" placeholder="Prix par heure (DT)" className="rounded-xl border border-slate-200 p-3" /><select name="governorate" className="rounded-xl border border-slate-200 p-3"><option value="">Gouvernorat</option>{governorates.map((item) => <option key={item}>{item}</option>)}</select><input name="city" placeholder="Ville" className="rounded-xl border border-slate-200 p-3" /></section><section><h2 className="text-lg font-bold">Matières enseignées</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{subjects.map((item) => <label key={item} className="flex items-center gap-2 rounded-lg border border-slate-200 p-2 text-sm"><input type="checkbox" name="subjects" value={item} />{item}</label>)}</div></section><section><h2 className="text-lg font-bold">Modes de cours</h2><div className="mt-3 flex gap-5 text-sm"><label><input type="checkbox" name="online" defaultChecked /> En ligne</label><label><input type="checkbox" name="inPerson" /> Présentiel</label></div></section><section><h2 className="text-lg font-bold">Disponibilités hebdomadaires</h2><div className="mt-3 space-y-2">{days.map((day, index) => <div key={day} className="grid grid-cols-[1fr_1fr_1fr] items-center gap-2 text-sm"><span>{day}</span><input type="time" name={`start-${index}`} className="rounded-lg border border-slate-200 p-2" /><input type="time" name={`end-${index}`} className="rounded-lg border border-slate-200 p-2" /></div>)}</div></section>{message && <p className="rounded-xl bg-[#e5f7f2] p-3 text-sm font-semibold text-[#0d8d78]">{message}</p>}<button disabled={pending} className="rounded-xl bg-[#0d8d78] px-6 py-3 font-bold text-white disabled:opacity-50">{pending ? "Envoi..." : "Soumettre ma candidature"}</button></form></div></main>;
}
